name: DevSpaceWeb publish

on:
  push:
     paths:
      - 'DevSpaceAgent/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x
          9.x
        
    - name: Restore dependencies
      run: dotnet restore "DevSpaceAgent/DevSpaceAgent.csproj"
      
    - name: Build
      run: dotnet build "DevSpaceAgent/DevSpaceAgent.csproj" --no-restore -r linux-x64 -c Release
      
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: dotnet publish "DevSpaceAgent/DevSpaceAgent.csproj" --no-build -r linux-x64 -c Release /p:PublishProfile=Github
