name: DevSpaceWeb publish

on:
  push:
     paths:
      - 'DevSpaceWeb/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore "DevSpaceWeb/DevSpaceWeb.csproj"
      
    - name: Build
      run: dotnet build "DevSpaceWeb/DevSpaceWeb.csproj" --no-restore -c Release
      
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: dotnet publish "DevSpaceWeb/DevSpaceWeb.csproj" --no-build -c Release /t:PublishContainer -p ContainerRegistry=ghcr.io
